const Constants = {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_ITINERARIES: 'FETCH_ITINERARIES',
    FETCH_ITINERARY: 'FETCH_ITINERARY',
    SET_ITINERARY: 'SET_ITINERARY',
}

export default Constants;