const Constants = {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_ITINERARIES: 'FETCH_ITINERARIES',
    FETCH_ITINERARY: 'FETCH_ITINERARY',
    SET_ITINERARY: 'SET_ITINERARY',
    FETCH_POSTS: 'FETCH_POSTS',
    SET_POSTS: 'SET_POSTS',
    FETCH_PLACES: 'FETCH_PLACES',
    FETCH_USER: 'FETCH_USER'
}

export default Constants;